

networks:
  hpm:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong!Passw0rd
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - hpm

  patient-api:
    image: dockeritc778/patient-api:latest
    container_name: patient-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    networks:
      - hpm

  appointment-api:
    image: dockeritc778/appointment-api:latest
    container_name: appointment-api
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - sqlserver
    networks:
      - hpm

  ui:
    image: dockeritc778/hpm:v5
    container_name: hospital-ui
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - patient-api
      - appointment-api
    networks:
      - hpm
