# values-ui.yaml

replicaCount: 1

metrics:
  enabled: false

image:
  repository: gcr.io/charged-thought-485008-q7/hospital-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

sqlserver:
  enabled: true

# ServiceAccount configuration
serviceAccount:
  create: true
  name: hospital-ui-sa

# No autoscaling
autoscaling:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Ingress configuration (UI release owns ingress)
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: hospital.34.173.19.139.nip.io
      paths:
        - path: /()(.*)
          pathType: ImplementationSpecific
          serviceName: hospital-ui-hpm
          servicePort: 80
        - path: /api/patients(/|$)(.*)
          pathType: ImplementationSpecific
          serviceName: hospital-patient-hpm
          servicePort: 3000
        - path: /api/appointments(/|$)(.*)
          pathType: ImplementationSpecific
          serviceName: hospital-appointment-hpm
          servicePort: 3001
  tls: []

# Node selector, tolerations, and affinity (optional)
nodeSelector: {}
tolerations: []
affinity: {}
